classifier_name: "ProbaLogisticRegression"
min_track_length: 20
proba_threshold: 0.8
random_state: 3
features_to_use:
  - "traversed_distance"
  - "average_distance_from_start"
  - "v_smoothed_std"
  - "average_pixel_intensity"
  - "stddev_of_intensity"
  - "v_95th_percentile"