classifier_name: "ProbaXGBClassifier"
min_track_length: 20
proba_threshold: 0.1
random_state: 3
features_to_use:
  - "v_50th_percentile"
  - "average_distance_from_start"
  - "v_95th_percentile"
  - "contour_area"
  - "average_distance_from_start/traversed_distance"