classifier_name: "ProbaXGBClassifier"
min_track_length: 20
proba_threshold: 0.5
random_state: 3
features_to_use:
  - 'traversed_distance'
  - 'v_95th_percentile'  
  - 'average_pixel_intensity' 
  - 'average_distance_from_start'
  - 'v_smoothed_avg'