output_directory: "/media/fish-pi/PortableSSD1/second_setup" # the directory must be located in the folder specified in the automounting command in /etc/fstab, consult continous_operation/raspberry_pi_setup_instructions.md for further information
watchdog_food_file: "/home/fish-pi/code/continous_operation/watchdog_food.csv"

recording_interval_minutes: 10
sleep_interval_minutes: 0.1
error_after_no_file_modification_minutes: 2

use_cloud: True
azure_container_name: "sonar-fish-prod"
raise_exception_on_cloud_error: True
