repos:
-   repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
    - id: isort
-   repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
    - id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
#-   repo: local -- uncomment when test are available
#    hooks:
#    -   id: pytest
#        name: pytest
#        entry: pytest
#        language: system
#        always_run: true
#        pass_filenames: false
#        types: [python]
#        stages: [push]
