pool:
  vmImage: 'ubuntu-latest'


stages:

- stage: Static_Tests
  dependsOn: [ ]
  displayName: Static Tests
  jobs:
  - job:
    displayName: Black, Isort, Flake 8
    steps:
      - task: UsePythonVersion@0
        displayName: Use Python 3.10
        inputs:
          versionSpec: 3.10
      - bash: |
          pip install -r requirements.txt
        displayName: Install dependencies
      - bash: |
          mypy .
        displayName: Check types
        continueOnError: true
      - script: |
          black . --check
        displayName: run black
      - script: |
          isort . --check-only --profile black
        displayName: run isort
      - script: |
          flake8 .
        displayName: flake8

- stage: Tests
  dependsOn: [ ]
  displayName: Tests
  jobs:
  - job:
    displayName: Pytest
    steps:
      - task: UsePythonVersion@0
        displayName: Use Python 3.10
        inputs:
          versionSpec: 3.10
      - bash: |
          pip install -r requirements.txt
        displayName: Install dependencies
      - script: |
          pytest
        displayName: Run tests

