# Code written by Leiv Andresen, HTD-A, leiv.andresen@axpo.com

# Output
output_video_dir: "output/videos/"
csv_output_directory: "output/csv/"

# Enhancement
downsample: 100
long_mean_frames: 120
current_mean_frames: 10
std_dev_threshold: 2
median_filter_kernel: 5  # 3

# Detection and Tracking
blur_filter_kernel: 11
threshold_contours: 200  # 139

max_association_dist: 120
phase_out_after_x_frames: 9
min_occurences_in_last_x_frames: [5, 10   ]

# Classification
river_pixel_velocity: [-1.91, -0.85]
rotation_rad: -2.7229