# Input / Output
# input_file:  "analysis/demo/22-11-14_start_16-46-57.mp4"
# input_file:  "analysis/demo/22-11-14_start_16-36-56_trim.mp4"
input_file:  "analysis/demo/22-11-14_start_16-36-56_trim_small.mp4"
mask_directory: "analysis/demo/masks"
output_directory: "analysis/1_productionalization/raspberry_pi_first_try/output"

tag: "fast_v2_runtime_test_rpi"
#record_output_video: True

#display_output_video: True
#display_mode_rich: True
#display_trackbars: True

# Enhancement
downsample: 25
long_mean_frames: 200
current_mean_frames: 10
std_dev_threshold: 1
median_filter_kernel: 3  # 3

# Detection and Tracking
blur_filter_kernel: 3
threshold_contours: 127  # 139

max_association_dist: 30
phase_out_after_x_frames: 10
min_occurences_in_last_x_frames: [13, 15]

river_pixel_velocity: [2.35, -0.9] # At full resolution
min_occurences_for_fish: 20
