# Code written by Leiv Andresen, HTD-A, leiv.andresen@axpo.com

# Input
input_directory: "data/raw/labels/"

# Output
csv_output_directory: "data/raw/labels/"
csv_output_suffix: "_ground_truth.csv"
overwrite_existing_csv: False

# Enhancement
four_images: False
fullres: True
downsample: 100
long_mean_frames: 120
current_mean_frames: 10
std_dev_threshold: 2
median_filter_kernel: 3  # 3

# Detection and Tracking
blur_filter_kernel: 9
threshold_contours: 35  # 139

max_association_dist: 35
phase_out_after_x_frames: 9
min_occurences_in_last_x_frames: [5, 10]

# Classification
river_pixel_velocity: [-1.91, -0.85]
rotation_rad: -2.7229