# Input / Output
file_name: "start_2023-11-21T17-37-01.696+00-00.mp4"
input_directory:  "data/raw/videos/"
mask_directory: "analysis/demo/masks"
output_directory: "data/model_output/"
ground_truth_directory: "data/labels/"
mask_file: "stroppel_non_object_space.png" # one of ["sonar_controls.png", "stroppel_non_object_space.png", "herrendoebeli_non_object_space.png"]

# Azure ML
experiment_name: "how_much_is_the_fish"
track_azure_ml: False

tag: "label"
record_output_video: False # Only works for full resolution output
record_processing_frame: "raw" # one of ['raw', 'raw_downsampled', 'gray', 'gray_boosted', 'long_mean', 'short_mean', 'difference', 'absolute_difference', 'difference_thresholded', 'difference_thresholded_abs', 'median_filter', 'binary', 'dilated']
draw_detections_on_saved_video: True
store_raw_image_patch: False
store_median_image_patch: False
show_detections: True
display_output_video: False
display_mode_extensive: False
display_trackbars: False
feature_to_load: "max_blob_count"

# Size
input_pixels_per_mm: 0.0838

# Enhancement
downsample: 25
contrast: 2
brightness: 30
long_mean_frames: 400
short_mean_frames: 10
difference_threshold_scaler: 0.30
dilation_kernel_mm: 500
median_filter_kernel_mm: 200
erosion_kernel_mm: 100


# Tracking
tracking_method: "kalman" # one of ['nearest_neighbor', 'kalman']
max_association_dist_mm: 500
phase_out_after_x_frames: 30
kalman_std_obj_initialization_factor: 0.1
kalman_std_obj_initialization_trace: [1, 1, 0.1, 1, 0.5, 0.5, 0.0001, 0.5] # [x, y, w, h, vx, vy, va, vh]
kalman_std_process_noise_factor: 0.2
kalman_std_process_noise_trace: [1, 1, 0.1, 1, 0.05, 0.05, 0.0001, 0.05] # [x, y, w, h, vx, vy, va, vh]
kalman_std_mmt_noise_factor: 0.5
kalman_std_mmt_noise_trace: [5, 1.7, 1, 0.05] # [x, y, a, h]
kalman_rotate_mmt_noise_in_river_direction: False
kalman_trace_history_matching_budget: 10
kalman_max_iou_distance: 0.5 # basically (1 - iou_min)
kalman_max_age: 35
kalman_n_init: 35
filter_nearest_neighbor:
filter_blob_matching_metric: "histogram" # one of ['euclidean_distance', 'blob_area', 'histogram', 'mutual_information', 'fft']
filter_association_thresh: 0.3
filter_blob_elimination_metric: "euclidean_distance" # one of ['euclidean_distance']
bbox_size_to_stddev_ratio_threshold: 100


# Classification
river_pixel_velocity: [2.35, -0.9] # At full resolution
min_occurences_for_fish: 20 # should be at least 20 for sensible calculation of velocity
deviation_from_river_velocity: 0.5

# Visualization
no_more_show_after_x_frames: 1
video_colormap: "red"