# Input / Output
input_file:  "analysis/labeling/start_2023-11-18T18-23-01.832+00-00/original.mp4"
mask_directory: "analysis/demo/masks"
output_directory: "analysis/labeling/start_2023-11-18T18-23-01.832+00-00"

tag: "label"
record_output_video: True # Only works for full resolution output
record_output_csv: True
record_processing_frame: "binary" # one of ['raw', 'raw_downsampled', 'gray', 'gray_boosted', 'long_mean', 'short_mean', 'difference', 'absolute_difference', 'difference_thresholded', 'difference_thresholded_abs', 'median_filter', 'binary', 'dilated']
draw_detections_on_saved_video: False

display_output_video: False
display_mode_extensive: False
display_trackbars: False

# Size
input_pixels_per_mm: 0.0838

# Enhancement
downsample: 25
contrast: 2
brightness: 30
long_mean_frames: 400
short_mean_frames: 10
difference_threshold_scaler: 0.3
dilation_kernel_mm: 770
median_filter_kernel_mm: 85

# Tracking
max_association_dist_mm: 600
phase_out_after_x_frames: 10

# Classification
river_pixel_velocity: [2.35, -0.9] # At full resolution
min_occurences_for_fish: 20 # should be at least 20 for sensible calculation of velocity
deviation_from_river_velocity: 0.5

# Visualization
no_more_show_after_x_frames: 1