# Input / Output
file_name: "start_2023-11-21T17-37-01.696+00-00.mp4"
input_directory:  "data/raw/"
mask_directory: "analysis/demo/masks"
output_directory: "data/model_output/"
ground_truth_directory: "data/labels/"

tag: "label"
record_output_video: True # Only works for full resolution output
record_output_csv: True
record_processing_frame: "raw" # one of ['raw', 'raw_downsampled', 'gray', 'gray_boosted', 'long_mean', 'short_mean', 'difference', 'absolute_difference', 'difference_thresholded', 'difference_thresholded_abs', 'median_filter', 'binary', 'dilated']
draw_detections_on_saved_video: False

display_output_video: True
display_mode_extensive: True
display_trackbars: False

# Size
input_pixels_per_mm: 0.0838

# Enhancement
downsample: 25
contrast: 2
brightness: 30
long_mean_frames: 400
short_mean_frames: 10
difference_threshold_scaler: 0.3
dilation_kernel_mm: 700
median_filter_kernel_mm: 340

# Tracking
tracking_method: "kalman" # one of ['nearest_neighbor', 'kalman']
max_association_dist_mm: 150
phase_out_after_x_frames: 30
filter_settings:
  kalman:
    std_obj_initialization_factor: 0.1
    std_obj_initialization_trace: [1, 1, 0.1, 1, 0.5, 0.5, 0.0001, 0.5] # [x, y, w, h, vx, vy, va, vh]
    std_process_noise_factor: 0.1
    std_process_noise_trace: [1, 1, 0.1, 1, 0.05, 0.05, 0.0001, 0.05] # [x, y, w, h, vx, vy, va, vh]
    std_mmt_noise_factor: 0.5
    std_mmt_noise_trace: [5, 1.7, 1, 0.05] # [x, y, a, h]
    rotate_mmt_noise_in_river_direction: False
    trace_history_matching_budget: 3
    max_iou_distance: 0.5 # basically (1 - iou_min)
    max_age: 30
    n_init: 35
  nearest_neighbor:
  blob_matching_metric: "blob_area" # one of ['euclidean_distance', 'blob_area']
  area_ratio_threshold: 0.97

# Classification
river_pixel_velocity: [2.35, -0.9] # At full resolution
min_occurences_for_fish: 20 # should be at least 20 for sensible calculation of velocity
deviation_from_river_velocity: 0.5

# Visualization
no_more_show_after_x_frames: 1
