# Input / Output
input_file:  "analysis/1_productionalization/validation_HTU_v1/recordings/22-11-14_start_16-36-56.mp4"
mask_directory: "analysis/1_productionalization/validation_HTU_v1/recordings/masks"
output_directory: "analysis/1_productionalization/validation_HTU_v1/output"

tag: "test_delete"
record_output_video: True
record_output_csv: True

display_output_video: True
display_mode_rich: True

# Enhancement
downsample: 25
long_mean_frames: 120
current_mean_frames: 10
std_dev_threshold: 2
median_filter_kernel: 5  # 3

# Detection and Tracking
blur_filter_kernel: 11
threshold_contours: 127  # 139

max_association_dist: 60
phase_out_after_x_frames: 5
min_occurences_in_last_x_frames: [13, 15]

# Classification
river_pixel_velocity: [-1.91, -0.85]
min_occurences_for_fish: 20