# Input / Output
#input_file:  "recordings/V2/v2_dev_test.mp4"
input_file:  "recordings/V2/Video 5_2022-05-27_051500_771_2141 ZU BESPRECHEN passage am Schluss.mp4"

record_output_video: "output/drei_farben_v2_test.mp4"
record_output_csv: "output/test_tracking_boxli_V2.csv"

# Enhancement
downsample: 100
long_mean_frames: 120
current_mean_frames: 10
std_dev_threshold: 2
median_filter_kernel: 5  # 3

# Detection and Tracking
blur_filter_kernel: 11
threshold_contours: 200  # 139

max_association_dist: 60
phase_out_after_x_frames: 1
min_occurences_in_last_x_frames: [5, 10   ]

# Classification
river_pixel_velocity: [-1.91, -0.85]
rotation_rad: -2.7229

# In the moment just detects on both channels,
#  needs to do it based on individuals though and then also
# handle the case of the dot in the middle.