# Input / Output
#input_file:  "recordings/V2/2022-05-29_053000_193_1241  v2_dev_test.mp4"
#input_file:  "recordings/V2/Video 5_2022-05-27_051500_771_2141 ZU BESPRECHEN passage am Schluss.mp4"

output_video_dir: "output/videos/"
csv_output_directory: "output/csv/"
input_directory: "recordings/V2/"

# Enhancement
downsample: 100
long_mean_frames: 120
current_mean_frames: 10
std_dev_threshold: 2
median_filter_kernel: 5  # 3

# Detection and Tracking
blur_filter_kernel: 11
threshold_contours: 200  # 139

max_association_dist: 60
phase_out_after_x_frames: 1
min_occurences_in_last_x_frames: [5, 10   ]

# Classification
river_pixel_velocity: [-1.91, -0.85]
rotation_rad: -2.7229