recording_directory: "/media/fish-pi/PortableSSD/test_rpi/recordings"
log_directory: "/media/fish-pi/PortableSSD/test_rpi/logs"
detections_directory: "/media/fish-pi/PortableSSD/test_rpi/detections"
file_list_directory: "/media/fish-pi/PortableSSD/test_rpi/file_lists"

recording_interval_minutes: 10
sleep_interval_minutes: 1
error_after_no_file_modification_minutes: 2

use_cloud: True
azure_container_name: "sonar-fish-prod"
raise_exception_on_cloud_error: True
