recording_directory: "/media/fishdisk/test_1/recordings"
log_directory: "/media/fishdisk/test_1/logs"
detections_directory: "/media/fishdisk/test_1/detections"
recording_interval_minutes: 10
sleep_interval_minutes: 1
error_after_no_file_modification_minutes: 2

use_cloud: True
azure_container_name: "sonar-fish-prod"
raise_exception_on_cloud_error: False
