name: Continuous Integration

on:
  push:
    branches:
      - '**'  # This triggers the workflow on a push to any branch
  pull_request:
    branches:
      - '**'  # This triggers the workflow for pull requests targeting any branch


jobs:
  static_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.0"
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Check types with mypy
        run: mypy .
        continue-on-error: true
      
      - name: Run black
        run: black . --check
      
      - name: Run isort
        run: isort . --check-only --profile black
      
      - name: Run flake8
        run: flake8 .
  
  tests:
    needs: static_tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Run tests
        run: |
          export PYTHONPATH=${PYTHONPATH}:$(pwd)
          cd tests
          pytest
